# Generated by Django 4.2.3 on 2023-07-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_produto_produto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
